/*
 * WHMCS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.clodesk.lib.whmcs_api_restfull_client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RequestAcceptOrder
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-12T14:57:36.589Z")
public class RequestAcceptOrder {
  @JsonProperty("orderid")
  private Integer orderid = null;

  @JsonProperty("serverid")
  private Integer serverid = null;

  @JsonProperty("serviceusername")
  private String serviceusername = null;

  @JsonProperty("servicepassword")
  private String servicepassword = null;

  @JsonProperty("registrar")
  private String registrar = null;

  @JsonProperty("sendregistrar")
  private Boolean sendregistrar = null;

  @JsonProperty("autosetup")
  private Boolean autosetup = null;

  @JsonProperty("sendemail")
  private Boolean sendemail = null;

  public RequestAcceptOrder orderid(Integer orderid) {
    this.orderid = orderid;
    return this;
  }

   /**
   * The order id to be accepted
   * @return orderid
  **/
  @ApiModelProperty(required = true, value = "The order id to be accepted")
  public Integer getOrderid() {
    return orderid;
  }

  public void setOrderid(Integer orderid) {
    this.orderid = orderid;
  }

  public RequestAcceptOrder serverid(Integer serverid) {
    this.serverid = serverid;
    return this;
  }

   /**
   * The specific server to assign to products within the order
   * @return serverid
  **/
  @ApiModelProperty(value = "The specific server to assign to products within the order")
  public Integer getServerid() {
    return serverid;
  }

  public void setServerid(Integer serverid) {
    this.serverid = serverid;
  }

  public RequestAcceptOrder serviceusername(String serviceusername) {
    this.serviceusername = serviceusername;
    return this;
  }

   /**
   * The specific username to assign to products within the order
   * @return serviceusername
  **/
  @ApiModelProperty(value = "The specific username to assign to products within the order")
  public String getServiceusername() {
    return serviceusername;
  }

  public void setServiceusername(String serviceusername) {
    this.serviceusername = serviceusername;
  }

  public RequestAcceptOrder servicepassword(String servicepassword) {
    this.servicepassword = servicepassword;
    return this;
  }

   /**
   * The specific password to assign to products within the order
   * @return servicepassword
  **/
  @ApiModelProperty(value = "The specific password to assign to products within the order")
  public String getServicepassword() {
    return servicepassword;
  }

  public void setServicepassword(String servicepassword) {
    this.servicepassword = servicepassword;
  }

  public RequestAcceptOrder registrar(String registrar) {
    this.registrar = registrar;
    return this;
  }

   /**
   * The specific registrar to assign to domains within the order
   * @return registrar
  **/
  @ApiModelProperty(value = "The specific registrar to assign to domains within the order")
  public String getRegistrar() {
    return registrar;
  }

  public void setRegistrar(String registrar) {
    this.registrar = registrar;
  }

  public RequestAcceptOrder sendregistrar(Boolean sendregistrar) {
    this.sendregistrar = sendregistrar;
    return this;
  }

   /**
   * Send the request to the registrar to register the domain.
   * @return sendregistrar
  **/
  @ApiModelProperty(value = "Send the request to the registrar to register the domain.")
  public Boolean isSendregistrar() {
    return sendregistrar;
  }

  public void setSendregistrar(Boolean sendregistrar) {
    this.sendregistrar = sendregistrar;
  }

  public RequestAcceptOrder autosetup(Boolean autosetup) {
    this.autosetup = autosetup;
    return this;
  }

   /**
   * Send the request to the product module to activate the service. This can override the product configuration.
   * @return autosetup
  **/
  @ApiModelProperty(value = "Send the request to the product module to activate the service. This can override the product configuration.")
  public Boolean isAutosetup() {
    return autosetup;
  }

  public void setAutosetup(Boolean autosetup) {
    this.autosetup = autosetup;
  }

  public RequestAcceptOrder sendemail(Boolean sendemail) {
    this.sendemail = sendemail;
    return this;
  }

   /**
   * Send any automatic emails. This can be Product Welcome, Domain Renewal, Domain Transfer etc.
   * @return sendemail
  **/
  @ApiModelProperty(value = "Send any automatic emails. This can be Product Welcome, Domain Renewal, Domain Transfer etc.")
  public Boolean isSendemail() {
    return sendemail;
  }

  public void setSendemail(Boolean sendemail) {
    this.sendemail = sendemail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestAcceptOrder requestAcceptOrder = (RequestAcceptOrder) o;
    return Objects.equals(this.orderid, requestAcceptOrder.orderid) &&
        Objects.equals(this.serverid, requestAcceptOrder.serverid) &&
        Objects.equals(this.serviceusername, requestAcceptOrder.serviceusername) &&
        Objects.equals(this.servicepassword, requestAcceptOrder.servicepassword) &&
        Objects.equals(this.registrar, requestAcceptOrder.registrar) &&
        Objects.equals(this.sendregistrar, requestAcceptOrder.sendregistrar) &&
        Objects.equals(this.autosetup, requestAcceptOrder.autosetup) &&
        Objects.equals(this.sendemail, requestAcceptOrder.sendemail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderid, serverid, serviceusername, servicepassword, registrar, sendregistrar, autosetup, sendemail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestAcceptOrder {\n");
    
    sb.append("    orderid: ").append(toIndentedString(orderid)).append("\n");
    sb.append("    serverid: ").append(toIndentedString(serverid)).append("\n");
    sb.append("    serviceusername: ").append(toIndentedString(serviceusername)).append("\n");
    sb.append("    servicepassword: ").append(toIndentedString(servicepassword)).append("\n");
    sb.append("    registrar: ").append(toIndentedString(registrar)).append("\n");
    sb.append("    sendregistrar: ").append(toIndentedString(sendregistrar)).append("\n");
    sb.append("    autosetup: ").append(toIndentedString(autosetup)).append("\n");
    sb.append("    sendemail: ").append(toIndentedString(sendemail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

