/*
 * WHMCS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.clodesk.lib.whmcs_api_restfull_client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * WhmcsResponseGeneric
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-12T13:15:38.447Z")
public class WhmcsResponseGeneric {
  @JsonProperty("result")
  private String result = null;

  @JsonProperty("message")
  private String message = null;

  public WhmcsResponseGeneric result(String result) {
    this.result = result;
    return this;
  }

   /**
   * The result of the operation: success or error
   * @return result
  **/
  @ApiModelProperty(value = "The result of the operation: success or error")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public WhmcsResponseGeneric message(String message) {
    this.message = message;
    return this;
  }

   /**
   * The message of error
   * @return message
  **/
  @ApiModelProperty(value = "The message of error")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WhmcsResponseGeneric whmcsResponseGeneric = (WhmcsResponseGeneric) o;
    return Objects.equals(this.result, whmcsResponseGeneric.result) &&
        Objects.equals(this.message, whmcsResponseGeneric.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WhmcsResponseGeneric {\n");
    
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

