/*
 * WHMCS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.clodesk.lib.whmcs_api_restfull_client.api;

import com.clodesk.lib.whmcs_api_restfull_client.invoker.ApiException;
import com.clodesk.lib.whmcs_api_restfull_client.model.RequestAcceptOrder;
import com.clodesk.lib.whmcs_api_restfull_client.model.RequestAddOrder;
import com.clodesk.lib.whmcs_api_restfull_client.model.RequestUpdateClientProduct;
import com.clodesk.lib.whmcs_api_restfull_client.model.WhmcsResponseErrorGeneric;
import com.clodesk.lib.whmcs_api_restfull_client.model.WhmcsResponseSuccessAcceptOrder;
import com.clodesk.lib.whmcs_api_restfull_client.model.WhmcsResponseSuccessAddOrder;
import com.clodesk.lib.whmcs_api_restfull_client.model.WhmcsResponseSuccessUpdateClientProduct;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Accepts a pending order
     *
     * Accepts a pending order
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void acceptOrderTest() throws ApiException {
        RequestAcceptOrder apiParameters = null;
        WhmcsResponseSuccessAcceptOrder response = api.acceptOrder(apiParameters);

        // TODO: test validations
    }
    
    /**
     * Add order
     *
     * Adds an order to a client.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addOrderTest() throws ApiException {
        RequestAddOrder apiParameters = null;
        WhmcsResponseSuccessAddOrder response = api.addOrder(apiParameters);

        // TODO: test validations
    }
    
    /**
     * Update client Product
     *
     * Updates a Client Service
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateClientProductTest() throws ApiException {
        RequestUpdateClientProduct apiParameters = null;
        WhmcsResponseSuccessUpdateClientProduct response = api.updateClientProduct(apiParameters);

        // TODO: test validations
    }
    
}
